apiVersion: v1
kind: Service
metadata:
  name: shivani-django-app-service
  # namespace: ingress-nginx
spec:
  type: LoadBalancer
  selector:
    app: django-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    # nodePort: 31253